[package]
name = "localtime"
description = "Minimal monotonic unix-time library"
authors = ["Alexis Sellier <self@cloudhead.io>"]
version = "1.2.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1", features = ["serde_derive"], optional = true }
